# Generated by Django 5.2.1 on 2025-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Checklist Item')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
