# Generated by Django 5.2.1 on 2025-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_itchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(choices=[('technical', 'Technical Issue'), ('hardware', 'Hardware Problem'), ('software', 'Software Problem'), ('access', 'Access Request'), ('trainig', 'IT training Request'), ('other', 'Other')], default='technical', max_length=20),
        ),
    ]
