# Generated by Django 5.2.1 on 2025-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ticket_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(choices=[('Technical', 'Technical Issue'), ('Hardware', 'Hardware Problem'), ('Software', 'Software Problem'), ('Access', 'Access Request'), ('Trainig', 'IT training Request'), ('Other', 'Other')], default='technical', max_length=20),
        ),
    ]
