# Generated by Django 5.2.2 on 2025-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ticket_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approx_solving_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(choices=[('Technical', 'Technical Issue'), ('Hardware', 'Hardware Problem'), ('Software', 'Software Problem'), ('Access', 'Access Request'), ('Training', 'IT training Request'), ('Other', 'Other')], default='technical', max_length=20),
        ),
    ]
